name: Firebase Continous Integration
on:
  push:
    branches: [ develop, master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    - name: Archive Build
      uses: actions/upload-artifact@master
      with:
        name: build
        path: build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Build
        uses: actions/download-artifact@master
        with:
          name: build
          path: build
      - name: Depoy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:stage
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
